services:
  backend:
    build: ./backend
    ports: 
      - 5000:5000 # local : container
    volumes:
      - ./data:/app/db
      - ./backend/src:/app/src
    env_file: ./backend/.env

  db: 
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file: ./backend/.env

  # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   ports: 
  #     - 3000:3000 # local : container
  #   volumes:
  #     - ./frontend/src:/app/src
